Use script to dynamically publish language packages

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -26,14 +26,22 @@ jobs:
         run: dotnet build -c Release
       - name: Publish Blism Package
         run: dotnet nuget push Blism/bin/Release/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
-      - name: Publish Blism.Language.CSharp Package
-        run: dotnet nuget push Blism.Language.CSharp/bin/Release/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
-      - name: Publish Blism.Language.Dart Package
-        run: dotnet nuget push Blism.Language.Dart/bin/Release/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
-      - name: Publish Blism.Language.Yaml Package
-        run: dotnet nuget push Blism.Language.Yaml/bin/Release/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
-      - name: Publish Blism.Language.Bash Package
-        run: dotnet nuget push Blism.Language.Bash/bin/Release/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
+      - name: Publish Language Packages
+        run: |
+          for folder in "$dir"/*/; do
+            folder_name=$(basename "$folder")
+            [[ "$folder_name" =~ \.Test$ ]] && continue
+
+            echo "::group::Publishing $folder_name"
+
+            {
+              dotnet nuget push $folder_name/bin/Release/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
+            } || {
+              echo "::error::Failed to publish $folder_name"
+            }
+
+            echo "::endgroup::"
+          done
       - name: Publish GitHub Release
         uses: softprops/action-gh-release@v2
         with:
